[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socketio-handler"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 